name: paper2
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - aiobotocore=2.12.2
  - aiohttp=3.9.3
  - aioitertools=0.11.0
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - archspec=0.2.3
  - asciitree=0.3.3
  - asttokens=2.4.1
  - attrs=23.2.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.14
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.6
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.5
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.4
  - aws-sdk-cpp=1.11.267
  - azure-core-cpp=1.11.1
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - blosc=1.21.5
  - bokeh=3.4.0
  - boltons=23.1.1
  - botocore=1.34.51
  - bounded-pool-executor=0.0.3
  - branca=0.7.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.3.11
  - cairo=1.18.0
  - cartopy=0.23.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfitsio=4.4.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - cmcrameri=1.9
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.2
  - conda=24.3.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.2.0
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.4.0
  - dask-core=2024.4.0
  - dask-expr=1.0.9
  - datashader=0.16.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - distributed=2024.4.0
  - distro=1.9.0
  - earthaccess=0.9.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - fasteners=0.17.3
  - fiona=1.9.6
  - fmt=10.2.1
  - folium=0.16.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.50.0
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.4.1
  - fsspec=2024.3.1
  - gdal=3.8.4
  - geopandas=0.14.3
  - geopandas-base=0.14.3
  - geos=3.12.1
  - geotiff=1.7.1
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - intel-openmp=2024.1.0
  - ipykernel=6.29.3
  - ipympl=0.9.4
  - ipython=8.22.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.2
  - itslive=0.3.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - jmespath=1.0.1
  - joblib=1.3.2
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.10
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.1
  - libaec=1.1.3
  - libarchive=3.7.2
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libdeflate=1.20
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgdal=3.8.4
  - libglib=2.80.0
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgrpc=1.62.1
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnetcdf=4.9.2
  - libparquet=15.0.2
  - libpng=1.6.43
  - libpq=16.2
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libsolv=0.7.28
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.6
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvmlite=0.42.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mamba=1.5.8
  - mapclassify=2.6.1
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - matplotlib-scalebar=0.8.1
  - mdurl=0.1.2
  - menuinst=2.0.2
  - minizip=4.0.5
  - mkl=2024.0.0
  - msgpack-python=1.0.7
  - msys2-conda-epoch=20160418
  - multidict=6.0.5
  - multimethod=1.11
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - noise=1.2.2
  - numba=0.59.1
  - numcodecs=0.12.1
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.0
  - orc=2.0.0
  - packaging=24.0
  - pandas=2.2.1
  - param=2.1.0
  - parso=0.8.3
  - partd=1.4.1
  - patsy=0.5.6
  - pcre2=10.43
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.4
  - planetary-computer=1.0.0
  - platformdirs=4.2.0
  - plotext=5.2.8
  - pluggy=1.4.0
  - poppler=24.03.0
  - poppler-data=0.4.12
  - postgresql=16.2
  - pqdm=0.2.0
  - proj=9.3.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pyarrow=15.0.2
  - pyarrow-hotfix=0.6
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pyct=0.5.0
  - pyct-core=0.5.0
  - pydantic=2.6.4
  - pydantic-core=2.16.3
  - pygments=2.17.2
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pystac=1.10.0
  - pystac-client=0.7.6
  - python=3.12.2
  - python-cmr=0.9.0
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pywin32=306
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - rasterio=1.3.9
  - re2=2023.09.01
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - rich=13.7.1
  - rich-click=1.7.4
  - rioxarray=0.15.3
  - rtree=1.2.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - s3fs=2024.3.1
  - scienceplots=2.1.1
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=69.2.0
  - shapely=2.0.3
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - spdlog=1.12.0
  - sqlite=3.45.2
  - stack_data=0.6.2
  - stackstac=0.5.0
  - statsmodels=0.14.1
  - tabulate=0.9.0
  - tbb=2021.11.0
  - tblib=3.0.0
  - threadpoolctl=3.4.0
  - tiledb=2.21.1
  - tinynetrc=1.3.1
  - tk=8.6.13
  - toolz=0.12.1
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.2
  - truststore=0.8.0
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - uriparser=0.9.7
  - urllib3=2.0.7
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - win_inet_pton=1.1.0
  - wrapt=1.16.0
  - xarray=2024.3.0
  - xarray-spatial=0.3.5
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.10.1
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.9.4
  - zarr=2.17.1
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
